# Generated by Django 5.1.2 on 2025-10-12 13:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='user',
            name='user_type',
        ),
        migrations.AlterField(
            model_name='localguide',
            name='experience_years',
            field=models.IntegerField(),
        ),
        migrations.AlterField(
            model_name='localguide',
            name='guide_photo',
            field=models.ImageField(blank=True, upload_to='guide_photos/'),
        ),
        migrations.AlterField(
            model_name='localguide',
            name='hourly_rate',
            field=models.DecimalField(decimal_places=2, max_digits=6),
        ),
        migrations.AlterField(
            model_name='localguide',
            name='rating',
            field=models.DecimalField(decimal_places=1, default=0.0, max_digits=3),
        ),
        migrations.AlterField(
            model_name='localguide',
            name='region',
            field=models.CharField(max_length=200),
        ),
        migrations.AlterField(
            model_name='user',
            name='email',
            field=models.EmailField(max_length=254, unique=True),
        ),
        migrations.AlterField(
            model_name='user',
            name='first_name',
            field=models.CharField(max_length=30),
        ),
        migrations.AlterField(
            model_name='user',
            name='last_name',
            field=models.CharField(max_length=30),
        ),
        migrations.AlterField(
            model_name='user',
            name='profile_picture',
            field=models.ImageField(blank=True, upload_to='profile_pics/'),
        ),
        migrations.DeleteModel(
            name='GuideReference',
        ),
    ]
