# Generated by Django 5.1.2 on 2025-10-12 13:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0002_remove_user_user_type_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='localguide',
            name='updated_at',
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AlterField(
            model_name='localguide',
            name='guide_photo',
            field=models.ImageField(blank=True, null=True, upload_to='guide_photos/'),
        ),
        migrations.AlterField(
            model_name='localguide',
            name='is_verified',
            field=models.BooleanField(default=True),
        ),
    ]
