# Generated by Django 5.1.2 on 2025-10-12 13:20

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bookings', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.RemoveField(
            model_name='itineraryday',
            name='itinerary',
        ),
        migrations.RemoveField(
            model_name='review',
            name='accommodation',
        ),
        migrations.RemoveField(
            model_name='review',
            name='destination',
        ),
        migrations.RemoveField(
            model_name='review',
            name='guide',
        ),
        migrations.RemoveField(
            model_name='review',
            name='user',
        ),
        migrations.AddField(
            model_name='accommodation',
            name='created_by',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='accommodation',
            name='updated_at',
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AddField(
            model_name='booking',
            name='updated_at',
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AlterField(
            model_name='accommodation',
            name='accommodation_type',
            field=models.CharField(choices=[('hotel', 'Hotel'), ('guesthouse', 'Guest House'), ('resort', 'Resort'), ('homestay', 'Homestay'), ('hostel', 'Hostel'), ('apartment', 'Apartment')], max_length=20),
        ),
        migrations.AlterField(
            model_name='accommodation',
            name='amenities',
            field=models.TextField(),
        ),
        migrations.AlterField(
            model_name='accommodation',
            name='check_in_time',
            field=models.TimeField(default='14:00'),
        ),
        migrations.AlterField(
            model_name='accommodation',
            name='check_out_time',
            field=models.TimeField(default='11:00'),
        ),
        migrations.AlterField(
            model_name='accommodation',
            name='image',
            field=models.ImageField(blank=True, upload_to='accommodations/'),
        ),
        migrations.AlterField(
            model_name='accommodation',
            name='max_guests',
            field=models.IntegerField(default=2),
        ),
        migrations.AlterField(
            model_name='accommodation',
            name='phone',
            field=models.CharField(max_length=20),
        ),
        migrations.AlterField(
            model_name='accommodation',
            name='rating',
            field=models.DecimalField(decimal_places=1, default=0.0, max_digits=3),
        ),
        migrations.AlterField(
            model_name='booking',
            name='payment_status',
            field=models.CharField(choices=[('pending', 'Pending'), ('paid', 'Paid'), ('failed', 'Failed'), ('refunded', 'Refunded')], default='pending', max_length=20),
        ),
        migrations.DeleteModel(
            name='Itinerary',
        ),
        migrations.DeleteModel(
            name='ItineraryDay',
        ),
        migrations.DeleteModel(
            name='Review',
        ),
    ]
